version: '3.3'

services:
  youtube-webapp:
    image: youtube-webapp
    restart: always
    build:
      context: ./src/
    container_name: youtube-webapp-c
    ports:
      - "5001:5003"
    volumes:
      - ./src:/app
